# Generated by Django 2.0.5 on 2018-05-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_issue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='issue',
            name='worked_time',
            field=models.FloatField(default=0.0),
        ),
    ]
