# Generated by Django 2.0.5 on 2018-06-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180531_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='total_time',
            new_name='estimate_time',
        ),
    ]
